language: node_js
node_js: "10"

cache:
  yarn: true
  directories: node_modules

addons:
  chrome: stable

notifications:
  email:
    on_failure: change
    on_success: change

matrix:
  include:
    - name: "Lint"
      script: yarn lint

    - name: "Pa11y"
      script: yarn pa11y:ci

    - name: "Unit"
      script: yarn test:ci

    - name: "E2E"
      script: yarn e2e:ci

    - name: "Deploy to Firebase"
      stage: deploy
      script: yarn build:ci
      deploy:
        skip_cleanup: true
        provider: firebase
        token:
          secure: $FIREBASE_TOKEN
        project: "slumber-numbers"
        on:
          branch: master
