sudo: required
dist: trusty

language: node_js

cache:
  yarn: true
  directories: node_modules

addons:
  chrome: stable

notifications:
  email:
    on_failure: change
    on_success: change

matrix:
  include:
    - env: MODE=lint
      node_js:
        - "9"
        - "10"
      script: yarn lint

    - env: MODE=pa11y
      node_js:
        - "9"
        - "10"
      script:
        - yarn start &
        - yarn wait
        - yarn test:pa11y

    - env: MODE=deploy
      node_js:
        - "9"
        - "10"
      script:
        - yarn build:ci
        - yarn test:ci
        - yarn e2e:ci
        - cat coverage/lcov.info | yarn coveralls

      deploy:
        skip_cleanup: true
        provider: firebase
        token:
          secure: $FIREBASE_TOKEN
        project: "slumber-numbers"
        on:
          branch: master
