language: node_js
node_js: "10"

cache:
  yarn: true
  directories: node_modules

addons:
  chrome: stable

notifications:
  email:
    on_failure: change
    on_success: change

matrix:
  include:
    - name: "Lint"
      script: yarn lint

    - name: "Pa11y"
      script:
        - yarn start &
        - yarn wait
        - yarn test:pa11y

    - name: "Unit, E2E, and Coverage"
      script:
        - yarn build:ci
        - yarn test:ci
        - yarn e2e:ci
        - cat coverage/lcov.info | yarn coveralls

    - stage: deploy
      name: "Deploy to Firebase"
      deploy:
        skip_cleanup: true
        provider: firebase
        token:
          secure: $FIREBASE_TOKEN
        project: "slumber-numbers"
        on:
          branch: master
