sudo: required
dist: trusty

language: node_js
node_js: "8"

addons:
  chrome: stable

cache:
  yarn: true
  directories: node_modules

script:
  - yarn build:all
  - yarn lint
  - yarn test:ci
  - yarn e2e:ci
  - cat coverage/lcov.info | yarn coveralls

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "slumber-numbers"
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change
